all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    vpn:
      vars:
        vpn_subnet: 10.100.0.0/16
        vpn_interface: wg0
        vpn_port: 51820
      hosts:
        azadi-1:
        azadi-2:
        azadi-3:
        azadi-4:
        azadi-5:
        iran-sos-1:
        iran-sos-2:
        iran-sos-3:
        iran-sos-4:
        iran-sos-5:

    conduit:
      hosts:
        azadi-1:
        azadi-2:
        azadi-3:
        azadi-4:
        azadi-5:
        iran-sos-1:
        iran-sos-2:
        iran-sos-3:
        iran-sos-4:
        iran-sos-5:

    edge:
      hosts:
        iran-sos-5:
